# Root → home
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Legacy → canonical (attorneys)
[[redirects]]
  from = "/attorneys"
  to = "/for-attorneys.html"
  status = 301
[[redirects]]
  from = "/attorney-pricing"
  to = "/for-attorneys.html"
  status = 301
[[redirects]]
  from = "/pricing"
  to = "/for-attorneys.html"
  status = 301

# Legacy → canonical (clients)
[[redirects]]
  from = "/subscription"
  to = "/for-clients.html"
  status = 301
[[redirects]]
  from = "/subscribe"
  to = "/for-clients.html"
  status = 301
[[redirects]]
  from = "/subscribe_es"
  to = "/for-clients.html"
  status = 301

# Pretty pay routes (swap to hosted checkout later)
[[redirects]]
  from = "/pay/clients"
  to = "/pay.html"
  status = 200
[[redirects]]
  from = "/pay/attorneys"
  to = "/pay.html"
  status = 200

# Fallback
[[redirects]]
  from = "/*"
  to = "/udl-404.html"
  status = 404
