[[redirects]]
  from = "/udl/*"
  to = "https://ultimadefensalegal.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/immigration/*"
  to = "https://ultimadefensalegal.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/legal/*"
  to = "https://ultimadefensalegal.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ultimadefensalegal/*"
  to = "https://ultimadefensalegal.com/:splat"
  status = 301
  force = true
