[[redirects]]
  from = "/index_es.html"
  to   = "/index.html"
  status = 301
  force = true
[[redirects]]
  from = "/subscribe_es.html"
  to   = "/subscribe.html"
  status = 301
  force = true
[[redirects]]
  from = "/attorneys_es.html"
  to   = "/attorneys.html"
  status = 301
  force = true
[[redirects]]
  from = "/404.es.html"
  to   = "/404.html"
  status = 301
  force = true
