# Netlify config for UDL (static site)
[build]
  publish = "."

# ------------------------------
# Friendly URLs + legacy fixes
# ------------------------------

# New York
[[redirects]]
  from = "/newyork-attorneys"
  to = "/newyork-attorneys.html"
  status = 301
[[redirects]]
  from = "/newyork-abogados"
  to = "/newyork-abogados.html"
  status = 301

# Miami
[[redirects]]
  from = "/miami-attorneys"
  to = "/miami-attorneys.html"
  status = 301
[[redirects]]
  from = "/miami-abogados"
  to = "/miami-abogados.html"
  status = 301

# Newark
[[redirects]]
  from = "/newark-attorneys"
  to = "/newark-attorneys.html"
  status = 301
[[redirects]]
  from = "/newark-abogados"
  to = "/newark-abogados.html"
  status = 301

# Chicago
[[redirects]]
  from = "/chicago-attorneys"
  to = "/chicago-attorneys.html"
  status = 301
[[redirects]]
  from = "/chicago-abogados"
  to = "/chicago-abogados.html"
  status = 301

# Philadelphia — canonical files in your repo:
#   EN = philadelphia-attorney.html  (singular)
#   ES = philadelphia-abogados.html  (plural)
[[redirects]]
  from = "/philadelphia-attorney"
  to = "/philadelphia-attorney.html"
  status = 301
[[redirects]]
  from = "/philadelphia-abogados"
  to = "/philadelphia-abogados.html"
  status = 301

# Legacy/stray names you may have created earlier:
[[redirects]]
  from = "/philadelphia-attorneys.html"
  to = "/philadelphia-attorney.html"
  status = 301
[[redirects]]
  from = "/philadelphia-attorneys"
  to = "/philadelphia-attorney.html"
  status = 301
[[redirects]]
  from = "/philadelphia-abogado"
  to = "/philadelphia-abogados.html"
  status = 301
[[redirects]]
  from = "/philadelphia-abogado.html"
  to = "/philadelphia-abogados.html"
  status = 301

# Optional: default fallback to homepage (keep commented if you have /404.html)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# ------------------------------
# Security & caching headers
# ------------------------------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https:; img-src 'self' https: data:; script-src 'self' https: 'unsafe-inline'; style-src 'self' https: 'unsafe-inline'; frame-ancestors 'self';"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Light cache for HTML (so edits show quickly)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"
